### ISSUE TITLE
"InvalidParameter.RoleArn: The parameter RoleArn is wrongly formed."

### ISSUE THREAD

**Issue by Jameshu229** [rockuw/node-sts-app-server#1]
你好，请问RoleArn是什么？怎么填写？

**Comment by rockuw** [comment]
在阿里云的官网控制台中：“访问控制” -> “角色管理” -> “角色详情”

**Comment by rockuw** [comment]
或者参考这个：https://help.aliyun.com/document_detail/oss/practice/ram_guide_dir/no_user_accout.html

**Comment by cloud-zhao** [comment]
#node index.js
/node-sts-app-server-master/index.js:19
  co(function\* () {
             ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by rockuw** [comment]
@cloud-zhao 你的node.js版本太低了，请使用4.x/5.x版本。

**Comment by lupengfeige** [comment]
你好，A simple app server using STS，这个demo我怎么启动不了

**Comment by lupengfeige** [comment]
npm WARN enoent ENOENT: no such file or directory, open 'C:\。。。\package
.json'

**Comment by rockuw** [comment]
``` bash
git clone https://github.com/rockuw/node-sts-app-server.git
cd node-sts-app-server
npm install
node index.js
```

**Comment by lupengfeige** [comment]
XMLHttpRequest cannot load http://localhost:3000/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by lupengfeige** [comment]
var appServer = 'http://localhost:3000';
var bucket = 'js-sdk-bucket-sts';
var region = 'oss-cn-hangzhou';
