### ISSUE TITLE
RoleArn字段是什么意思？

### ISSUE THREAD

**Issue by kimmy-wang** [rockuw/node-sts-app-server#2]
你好，config.json中的这个“RoleArn”字段代表啥意思？

**Comment by kimmy-wang** [comment]
{ Error: NoPermission: No permission perform sts:AssumeRole on this Role. Maybe you are not authorized to perform sts:AssumeRole or the specified role does not trust y
ou
    at STS._requestError (F:\work\work\web\aliyun-oss-node\server\node_modules\ali-oss\lib\sts.js:116:13)
    at _requestError.next (<anonymous>)
    at onFulfilled (F:\work\work\web\aliyun-oss-node\server\node_modules\co\index.js:65:19)
    at F:\work\work\web\aliyun-oss-node\server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (F:\work\work\web\aliyun-oss-node\server\node_modules\co\index.js:50:10)
    at toPromise (F:\work\work\web\aliyun-oss-node\server\node_modules\co\index.js:118:63)
    at next (F:\work\work\web\aliyun-oss-node\server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\work\work\web\aliyun-oss-node\server\node_modules\co\index.js:69:7)
    at <anonymous>
  status: 403,
  code: 'NoPermission',
  message: 'NoPermission: No permission perform sts:AssumeRole on this Role. Maybe you are not authorized to perform sts:AssumeRole or the specified role does not trus
t you',
